version: 0.2

env:
  variables:
    S3_BUCKET: "tastingswithtay-cf-iac-common-components"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - aws --version
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      # Package Lambda files, in a zip, to be used in the build stage.
      - cd lambda
      - for d in */; do zip -r "${d%/}.zip" "$d"; done # zip all subdirectories in lambda
      - cd ..

      # Package Templates, into a s3, so we can use Nested Stacks.
      - aws s3 sync stacks s3://${S3_BUCKET}
      - aws s3 sync lambda s3://${S3_BUCKET}/lambda # sync zipped lambda files to S3 bucket
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
