version: 0.2

env:
  variables:
    TEMP: "tastingswithtay-cf-iac-common-components"
    S3_BUCKET: "your-s3-bucket-name" # Replace with your S3 bucket name

phases:
  install:
    commands:
      - echo Entered the install phase...
      - aws --version
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - ls -l
      - aws s3 sync /stacks s3://${S3_BUCKET}/stacks # Upload all files under /stacks to the S3 bucket

artifacts:
  files:
    - "**/*"
