version: 0.2

env:
  variables:
    S3_BUCKET: "tastingswithtay-cf-iac-common-components"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - aws --version
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - aws s3 sync stacks s3://${S3_BUCKET} # Upload all files under /stacks to the S3 bucket
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
