######################################################################################
# Wraps and creates teh entire AWS foundation supporting tastingswithtay
#
# Using this foundation, you will get the folloiwng setup.
#
#    1. Networking configuraitons.
#    2. CICD process setup.
#    3. Compute setup to expose a ReactJS application.
#    4. Lmabda, APIGateway, and ELD connevtivity.
#
# The CI process for this foundation runs on AWS CodePipeline. We wraped it in such
# a way, so we only have to have one CodeDeploy, for the foundaiton, which then can
# deploy the ohter stacks.
######################################################################################
AWSTemplateFormatVersion: "2010-09-09"
Description: "Foundational Configurations for tastingswithtay"
Parameters:
  ENV:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
    Description: "Environment (dev, prod)"
  Project:
    Type: String
    Default: "tastingswithtay"
    Description: "Project name"
  TaskCount:
    Type: Number
    Default: 1
    Description: "Number of ECS tasks to provision"
  ECRRepoUri:
    Type: String
    Default: "007794960432.dkr.ecr.us-east-1.amazonaws.com/tastingswithtay-ui:latest"
    Description: "ECR Repo UI for docker."
  Owner:
    Type: String
    Default: "DaveVED"
    Description: "GitHub repository owner"
  Repo:
    Type: String
    Default: "tastingswithtay-ui"
    Description: "GitHub repository name"
  Branch:
    Type: String
    Default: "develop"
    Description: "GitHub repository branch name"

Resources:
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/networking.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
  Compute:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Networking
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/compute.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
        ECRRepoUri: !Ref ECRRepoUri
        TaskCount: !Ref TaskCount
  DevPipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Networking
      - Compute
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/pipeline.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
        Owner: !Ref Owner
        Repo: !Ref Repo
        Branch: !Ref Branch
        TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:007794960432:targetgroup/tastin-EcsTa-50N97VUXQJ8I/2cfe74303ab2804f"
