AWSTemplateFormatVersion: "2010-09-09"
Description: "Foundational Configurations for tastingswithtay"
Parameters:
  ENV:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
    Description: "Environment (dev, prod)"
  Project:
    Type: String
    Default: "tastingswithtay"
    Description: "Project name"

Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/networking.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
  StorageStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkingStack
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/storage.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkingStack
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/compute.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkingStack
      - ComputeStack
      - StorageStack
    Properties:
      TemplateURL: "https://tastingswithtay-cf-iac-common-components.s3.amazonaws.com/api.yaml"
      Parameters:
        ENV: !Ref ENV
        Project: !Ref Project
