######################################################################################################
# Creats the core common compute components for https://tastingswithtays.com
#
# Using this compute.yaml temaplte, you will get a compute configuration with the following setup.
#    1. ECS Cluster, with encryption, logging, and container insights.
#    2. ECS Task definition working with the ECR for your UI.
#    3. ECS Service to Mange the required number of provisioned tasks.
#    4. ALB to front as an entry point.
#    5. Route53 + SSL support.
#
# For the three tier applicaiotn, this is enough infrastruce to support, no need to use EKS.
######################################################################################################
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ENV:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
    Description: "Environment (dev, prod)"
  Project:
    Type: String
    Default: "tastingswithtay"
    Description: "Project name"
  TaskCount:
    Type: Number
    Default: 1
    Description: "Number of ECS tasks to provision"
  ECRRepoUri:
    Type: String
    Default: "007794960432.dkr.ecr.us-east-1.amazonaws.com/tastingswithtay-ui:latest"
    Description: "ECR Repo UI for docker."
Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Sub "${Project}-${ENV}-cluster"
      Configuration:
        ExecuteCommandConfiguration:
          KmsKeyId: !Ref KmsKeyAlias
          Logging: OVERRIDE
          LogConfiguration:
            CloudWatchEncryptionEnabled: true
            CloudWatchLogGroupName: !Ref CloudwatchLogsGroup
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: "Name"
          Value: !Sub "${Project}-${ENV}-cluster"
  EcsSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: ECS Security Group
      VpcId: !ImportValue VPC
  EcsSecurityGroupHTTPinbound:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref EcsSecurityGroup
  EcsSecurityGroupALB:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref ALBSecurityGroup
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !ImportValue VPC
  ALBSecurityGroupHTTPinbound:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref ALBSecurityGroup
  ALBSecurityGroupALB:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: 70.123.176.84/32
  KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
  KmsKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${Project}-${ENV}-ECSKey"
      TargetKeyId: !Ref KmsKey
  CloudwatchLogsGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "${Project}-${ENV}-ECSLogGroup"
      RetentionInDays: 14
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Project}-${ENV}-ecs-task-execution"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${Project}-${ENV}-ecs-tasks"
      RetentionInDays: 14
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Project}-${ENV}"
      Cpu: "512"
      NetworkMode: "awsvpc"
      Memory: "2048"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RequiresCompatibilities:
        - "FARGATE"
      ContainerDefinitions:
        - Name: !Sub "${Project}-${ENV}"
          Image: !Ref ECRRepoUri
          Cpu: "512"
          Memory: "2048"
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Sub "${Project}-${ENV}"
          HealthCheck:
            Retries: 5
            Interval: 120
            Timeout: 60
            StartPeriod: 300
            Command: ["CMD-SHELL", "echo hello"]
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Sub "${Project}-${ENV}-service"
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: "FARGATE"
      DesiredCount: !Ref TaskCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split [",", !ImportValue PrivateSubnets]
          SecurityGroups: [!Ref EcsSecurityGroup]
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: !Sub "${Project}-${ENV}"
          ContainerPort: 3000
          TargetGroupArn: !Ref EcsTargetGroup
  EcsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Project}-${ENV}-alb"
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets: !Split [",", !ImportValue PublicSubnets]
      SecurityGroups: [!Ref ALBSecurityGroup]
      Tags:
        - Key: "Name"
          Value: !Sub "${Project}-${ENV}-alb"
  EcsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 180
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: "200-399"
      Tags:
        - Key: "Name"
          Value: !Sub "${Project}-${ENV}-target-group"
  ECSServiceListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref EcsTargetGroup
          Type: forward
      LoadBalancerArn: !Ref EcsLoadBalancer
      Port: 80
      Protocol: HTTP
