AWSTemplateFormatVersion: "2010-09-09"
Description: "Storage solutions for tastingswithtay"
Parameters:
  ENV:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
    Description: "Environment (dev, prod)"
  Project:
    Type: String
    Default: "tastingswithtay"
    Description: "Project name"
Resources:
  Assets:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${Project}-${ENV}-assets"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref s3Key
              SSEAlgorithm: aws:kms
  s3Key:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "My KMS key for S3 encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Enable S3 Bucket Permissions"
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action:
              - "kms:GenerateDataKey*"
              - "kms:Decrypt"
            Resource: "*"
  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Project}-${ENV}-content"
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: N
        - AttributeName: sortKey
          AttributeType: S
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
